added all examples for How I Leaped Forward My Jenkins Build with JFr…
jfrog/project-examples pull request #244
Opened 2020-12-13 13:14 UTC by talitz

…og Pipelines blog post

2020-12-13 13:15 UTC, talitz commented
I have read the CLA Document and I hereby sign the CLA

2020-12-13 14:18 UTC, eyalbe4 requested changes
Thanks for creating this PR!
See my inline comments. Notice that some of them also apply for other places in your code, and not just the specific lines.

2020-12-13 14:18 UTC, eyalbe4 commented on jenkins-examples/pipeline-examples/declarative-examples/jenkins-with-jfrog-pipelines/Jenkinsfile
> +                    id: "talyi-artifactory",
Let's use a more generic server ID, similarly to the other examples.

2020-12-13 14:18 UTC, eyalbe4 commented on jenkins-examples/pipeline-examples/declarative-examples/jenkins-with-jfrog-pipelines/ci-jenkins-cd-pipelines/Jenkinsfile
> +
Redundant new-line.

2020-12-13 14:18 UTC, eyalbe4 commented on jenkins-examples/pipeline-examples/declarative-examples/jenkins-with-jfrog-pipelines/ci-jenkins-cd-pipelines/Jenkinsfile
> +
Redundant new-line.

2020-12-13 14:18 UTC, eyalbe4 commented on jenkins-examples/pipeline-examples/declarative-examples/jenkins-with-jfrog-pipelines/Jenkinsfile
> +                  sh "cd target && ls -la"
Let's remove this step.

2020-12-13 14:49 UTC, talitz commented
I have read the CLA Document and I hereby sign the CLA

2020-12-15 11:31 UTC, eyalbe4 requested changes
Thanks @talitz!
There's something else I noticed that is missing. Can you please add your new example to the README in https://github.com/jfrog/project-examples/tree/master/jenkins-examples/pipeline-examples/declarative-examples?

2020-12-15 11:39 UTC, talitz commented
@eyalbe4 - thanks. resolved!

2020-12-17 11:46 UTC, talitz commented
Hi @eyalbe4 - anything else that should be added here?

2020-12-27 09:24 UTC, eyalbe4 approved these changes

2020-12-27 09:25 UTC, merged

2020-12-27 09:26 UTC, eyalbe4 commented
Thanks @talitz!
Approved and merged.
Please go ahead and create another PR, which updates your blog post link in the README.