Adding yarn examples
jfrog/project-examples pull request #374
Opened 2023-09-20 13:20 UTC by eranturgeman

added 2 folders:
yarn-v1 (for yarn classic)
yarn-v2 (for yarn v2 and yarn berry [v3])

2023-09-20 13:27 UTC, yahavi requested changes
Please also add README.md. See the npm-example for reference.

2023-09-20 13:27 UTC, yahavi commented on yarn-examples/yarn-v2/package.json
> +  "name": "yarn-v2",
Let's also rename the name of the directory
```suggestion
  "name": "yarn-berry",
```

2023-09-20 13:41 UTC, sverdlov93 commented on yarn-examples/yarn-v2/package.json
> +  "description": "yarn v2 example project",
v2?

2023-09-20 16:31 UTC, sverdlov93 commented on yarn-examples/yarn-berry/README.md
> +(or just jf yarn config and follow UI instructions)
```suggestion
```

2023-09-20 16:31 UTC, sverdlov93 commented on yarn-examples/yarn-v1/README.md
> +(or just jf yarn config and follow UI instructions)
```suggestion
```

2023-09-20 16:36 UTC, sverdlov93 commented on yarn-examples/yarn-v1/README.md
> +> jf rt bp my-build 1
```suggestion
// Build the project with yarn
jf yarn install
```

2023-09-21 08:32 UTC, sverdlov93 commented on yarn-examples/yarn-v1/README.md
> +Yarn classic projects are not fully supported by Artifactory as Yarn Berry projects.
```suggestion
```

2023-09-21 08:32 UTC, sverdlov93 commented on yarn-examples/yarn-berry/README.md
> +Artifactory supports all Yarn Berry versions but Build operation is currently not supported for projects with version prior to 2.4.0
```suggestion
```

2023-09-21 12:48 UTC, merged